spring:
  application:
    name: blueprint-manager
  profiles:
    active: redis
  session:
    store-type: none
#  output:
#    ansi:
#      enabled: ALWAYS
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${oauth.tokenprovider.url}/.well-known/jwks.json
server:
  error:
    whitelabel:
      enabled: false
  servlet:
    session:
      timeout: 30m
blueprint-manager:
  version: @app.version@
  env: ${app.env}

---

spring:
  profiles: redis
  session:
    store-type: redis
    redis.namespace: blueprint-manager-${app.version}:session